version: '3'
services:
  web:
    image: nginx
    ports:
      - 9090:80

  database:
    image: redis

---

- hosts: webservers
  become: true
  become_user: root
  tasks:
     - name: User Account Creation
       user:
        name: jai
        uid: 1021
        state: present
...
